# 1. Google Play Store Reviews

**List of apps:**

| App	| Link |   
| --- | --- |  
| Wysa: Anxiety, therapy chatbot | https://play.google.com/store/apps/details?id=bot.touchkin |
| Woebot: The Mental Health Ally | https://play.google.com/store/apps/details?id=com.woebot |
| Youper - CBT Therapy Chatbot | https://play.google.com/store/apps/details?id=br.com.youper |
| Sintelly: CBT Therapy Chatbot | https://play.google.com/store/apps/details?id=com.seasector.emotionalintelligence |


## Required library downloads

In [827]:
#!pip install google_play_scraper -q

In [828]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [829]:
from google_play_scraper import app # app details
from google_play_scraper import Sort, reviews_all # all reviews

## Wysa: Anxiety, therapy chatbot

Link: https://play.google.com/store/apps/details?id=bot.touchkin

ID: bot.touchkin

In [831]:
id1 = 'bot.touchkin'

In [832]:
wysa_details = app(id1, lang='en', country='us')
#wysa_details

In [833]:
# Count/No. of reviews
wysa_details['reviews']

17543

In [834]:
wysa_reviews = reviews_all(
    id1,
    # sleep_milliseconds = 0, # defaults to 0
    # lang = 'en', # defaults to 'en'
    # country = 'us', # defaults to 'us'
    # sort = Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
    # count = 3, # defaults to 100
    # filter_score_with = 5, # defaults to None(means all score)
)
#wysa_reviews

In [835]:
wysa_all = pd.json_normalize(wysa_reviews)
wysa_all.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,8808579a-2e65-48c6-9c18-187f2c8d0343,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,It's helping me so much 😊,5,0,3.7.3,2024-12-23 11:20:38,None,NaT,3.7.3
1,3db07453-3516-4dd5-9924-190af102e811,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,it's a bit hard to use but it does the job of ...,4,0,3.7.3,2024-12-23 06:16:35,None,NaT,3.7.3
2,4f1e8461-d44c-4be1-895e-fadb9b819a19,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,it really helped,5,0,None,2024-12-23 05:44:04,None,NaT,None
3,c2938b84-03cd-41f9-a982-4d24b29c9116,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,it's great,5,0,3.7.3,2024-12-22 23:06:48,None,NaT,3.7.3
4,41074d25-5dbd-4903-a1e1-606a242d66e6,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,great I've been using this app for a few min a...,5,0,3.7.3,2024-12-22 16:09:18,Thank you for taking the time to leave us a re...,2024-12-23 06:08:52,3.7.3

In [836]:
wysa_all.isnull().sum()

reviewId                    0
userName                    0
userImage                   0
content                     0
score                       0
thumbsUpCount               0
reviewCreatedVersion     2994
at                          0
replyContent            36189
repliedAt               36189
appVersion               2994
dtype: int64

In [837]:
wysa_all['content'].count()

45904

In [838]:
wysa_all.to_csv('review_data/wysa_reviews.csv', index=False)

In [839]:
all_reviews = wysa_all[['content', 'score']]
all_reviews['source'] = 'wysa'
all_reviews.head(10)

                                             content  score source
0                          It's helping me so much 😊      5   wysa
1  it's a bit hard to use but it does the job of ...      4   wysa
2                                   it really helped      5   wysa
3                                         it's great      5   wysa
4  great I've been using this app for a few min a...      5   wysa
5  it is really helpful to understand our thought...      4   wysa
6  I like this app, it's comforting, it isn't an ...      5   wysa
7  It really helps to talk about anything and off...      5   wysa
8  Really great app, i can't afford a real therap...      5   wysa
9                    its very helpful to my studying      5   wysa

In [840]:
all_reviews.columns

Index(['content', 'score', 'source'], dtype='object')

In [841]:
# renaming
all_reviews.rename(columns={'content': 'review', 'score': 'sentiment'}, inplace=True)
all_reviews.head(10)

                                              review  sentiment source
0                          It's helping me so much 😊          5   wysa
1  it's a bit hard to use but it does the job of ...          4   wysa
2                                   it really helped          5   wysa
3                                         it's great          5   wysa
4  great I've been using this app for a few min a...          5   wysa
5  it is really helpful to understand our thought...          4   wysa
6  I like this app, it's comforting, it isn't an ...          5   wysa
7  It really helps to talk about anything and off...          5   wysa
8  Really great app, i can't afford a real therap...          5   wysa
9                    its very helpful to my studying          5   wysa

In [842]:
print(len(all_reviews))

45904

In [843]:
all_reviews.to_csv('all_reviews.csv', index=False)

## Woebot: The Mental Health Ally

Link: https://play.google.com/store/apps/details?id=com.woebot

ID: com.woebot

In [845]:
id2 = 'com.woebot'

In [846]:
details_woebot = app(id2, lang='en', country='us')
#details_woebot

In [847]:
# Count/No. of reviews
details_woebot['reviews']

2572

In [848]:
'''
sleep_milliseconds=0, # defaults to 0
lang='en', # defaults to 'en'
country='us', # defaults to 'us'
sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT/Sort.NEWEST
count=3, # defaults to 100
filter_score_with=5 # defaults to None(means all score)
'''

woebot_reviews = reviews_all(
    id2,
    #sleep_milliseconds=0, # defaults to 0
    #lang='en', # defaults to 'en'
    #country='us', # defaults to 'us'
    #sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
)
#woebot_reviews

In [849]:
woebot_all = pd.json_normalize(woebot_reviews)
#woebot_all
woebot_all.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,65b3c42c-8ed8-48e3-aa66-0f3bca81e8f3,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,How do i get the access? I downloaded with a g...,1,0,None,2024-11-21 11:44:03,Sorry to disappoint! Woebot is only currently ...,2024-11-22 10:06:45,None
1,0b36862e-d639-41e7-a368-57d7d145e552,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Why must you have an access code? Why is it no...,1,0,6.6.0,2024-11-18 18:12:57,We appreciate your interest and regret that Wo...,2024-11-20 12:21:32,6.6.0
2,fa63553d-a7a0-483c-8ba9-8631a76a0c9d,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,I love this app! I have struggled with my ment...,3,0,5.3.0,2024-11-09 01:23:34,Thank you! We appreciate you getting in touch ...,2023-05-15 15:16:11,5.3.0
3,fb625861-a869-4f3b-a4f0-f5ca99b9435c,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Really helps me out,5,0,6.5.0,2024-11-06 18:30:33,"Thank you, Jason! We're glad that Woebot's bee...",2024-11-07 15:50:38,6.5.0
4,16a60c3c-531e-4253-a752-8c9115c7bea9,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,Love this app. Won't take the place of a thera...,5,1,6.5.1,2024-10-31 22:44:57,We're glad to hear that Woebot's been such a u...,2024-11-01 15:41:59,6.5.1

In [850]:
woebot_all['content'].count()

5461

In [851]:
woebot_all.to_csv('review_data/woebot_reviews.csv')

In [852]:
selected = woebot_all[['content','score']]
selected.rename(columns={'content': 'review', 'score': 'sentiment'}, inplace=True)
selected['source'] = "woebot"
selected

                                                 review  sentiment  source
0     How do i get the access? I downloaded with a g...          1  woebot
1     Why must you have an access code? Why is it no...          1  woebot
2     I love this app! I have struggled with my ment...          3  woebot
3                                   Really helps me out          5  woebot
4     Love this app. Won't take the place of a thera...          5  woebot
...                                                 ...        ...     ...
5456  app asked phone number at install. i just unin...          1  woebot
5457  Permissions, why do you need my photos and cal...          1  woebot
5458                    Needs a verifiable phone number          1  woebot
5459                  Why should I give you my number ?          1  woebot
5460                                    Very well done.          5  woebot

[5461 rows x 3 columns]

In [853]:
all_reviews = pd.concat([all_reviews, selected], ignore_index=True)
all_reviews.tail(10)

                                                  review  sentiment  source
51355                                             ... :(          1  woebot
51356                              why phone number.....          1  woebot
51357  It takes my number but i didn't recieve any co...          1  woebot
51358                      Phone number and media access          1  woebot
51359                               Require phone number          1  woebot
51360  app asked phone number at install. i just unin...          1  woebot
51361  Permissions, why do you need my photos and cal...          1  woebot
51362                    Needs a verifiable phone number          1  woebot
51363                  Why should I give you my number ?          1  woebot
51364                                    Very well done.          5  woebot

In [854]:
len(all_reviews)

51365

In [855]:
# Cross check the number of reviews from two apps
len(wysa_all) + len(woebot_all)

51365

In [856]:
all_reviews.to_csv('all_reviews.csv', index=False)

In [857]:
len(all_reviews)

51365

## Youper - CBT Therapy Chatbot

Link: https://play.google.com/store/apps/details?id=br.com.youper

ID: br.com.youper

In [859]:
id3 = 'br.com.youper'

In [860]:
details_youper = app(id3, lang='en', country='us')
#details_youper

In [861]:
# Count/No. of reviews
details_youper['reviews']

9006

In [862]:
'''
sleep_milliseconds=0, # defaults to 0
lang='en', # defaults to 'en'
country='us', # defaults to 'us'
sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT/Sort.NEWEST
count=3, # defaults to 100
filter_score_with=5 # defaults to None(means all score)
'''

youper_all = reviews_all(
    id3,
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
)
#youper_all

In [863]:
youper_all = pd.json_normalize(youper_all)
#youper_all
youper_all.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,4d4f98ce-e2e8-46cf-95ee-87543822076d,Jennifer Wiebusch,https://play-lh.googleusercontent.com/a-/ALV-U...,I signed up for the free trial to see how it w...,1,9,12.06.009,2024-11-24 17:14:29,We’re sorry to hear about your experience and ...,2024-11-25 00:35:44,12.06.009
1,c16b9538-e2ed-4511-8414-641b45ecb2e5,Dana Estipona,https://play-lh.googleusercontent.com/a-/ALV-U...,I went ahead and took the plunge to update my ...,1,3,10.09.000,2024-11-30 12:26:16,We're truly sorry for the loss of your data an...,2024-12-02 00:52:53,10.09.000
2,41c9f221-5804-44d9-af62-18531925ce05,Anna Brown,https://play-lh.googleusercontent.com/a-/ALV-U...,In free trial now. Conversations seem like the...,2,9,12.06.002,2024-08-25 22:42:01,Thank you for your feedback. We understand how...,2024-08-26 01:31:30,12.06.002
3,d79da936-6877-4df8-a2a0-2fa70e3622d0,Colten Schmidt,https://play-lh.googleusercontent.com/a/ACg8oc...,**edit: Years ago this app was free and had a ...,1,6,7.00.004,2022-04-13 21:57:57,"That's awesome, Colten! Thank you for sharing ...",2018-04-20 12:15:32,7.00.004
4,b646b2ef-c34f-4c86-a374-215ff0f0753f,Jamie,https://play-lh.googleusercontent.com/a-/ALV-U...,I'm extremely upset to see this app get stuck ...,1,84,12.06.002,2024-04-24 23:33:55,We're very sorry to hear about your recent exp...,2024-05-21 12:15:29,12.06.002

In [864]:
len(youper_all)

16546

In [865]:
youper_all.to_csv('review_data/youper_reviews.csv')

In [866]:
selected = youper_all[['content','score']]
selected.rename(columns={'content': 'review', 'score': 'sentiment'}, inplace=True)
selected['source'] = "youper"
selected

                                                  review  sentiment  source
0      I signed up for the free trial to see how it w...          1  youper
1      I went ahead and took the plunge to update my ...          1  youper
2      In free trial now. Conversations seem like the...          2  youper
3      **edit: Years ago this app was free and had a ...          1  youper
4      I'm extremely upset to see this app get stuck ...          1  youper
...                                                  ...        ...     ...
16541                                                 👍❤          5  youper
16542                                          thank you          5  youper
16543                                          Thank you          5  youper
16544                                                 😍😍          5  youper
16545                                                . .          5  youper

[16546 rows x 3 columns]

In [867]:
all_reviews = pd.concat([all_reviews, selected], ignore_index=True)
all_reviews.tail(10)

          review  sentiment  source
67901        Wow          5  youper
67902       okat          5  youper
67903        Wow          5  youper
67904       Dope          5  youper
67905     Yassss          5  youper
67906         👍❤          5  youper
67907  thank you          5  youper
67908  Thank you          5  youper
67909         😍😍          5  youper
67910        . .          5  youper

In [868]:
len(all_reviews)

67911

In [869]:
# Cross check the number of reviews from three apps
len(wysa_all) + len(woebot_all) + len(youper_all)

67911

In [870]:
all_reviews.to_csv('all_reviews.csv', index=False)

In [871]:
len(all_reviews)

67911

## Sintelly: CBT Therapy Chatbot

Link: https://play.google.com/store/apps/details?id=com.seasector.emotionalintelligence

ID: com.seasector.emotionalintelligence

In [873]:
id4 = 'com.seasector.emotionalintelligence'

In [874]:
details_sintelly = app(id4, lang='en', country='us')
#details_sintelly

In [875]:
# Count/No. of reviews
details_sintelly['reviews']

1026

In [876]:
'''
sleep_milliseconds=0, # defaults to 0
lang='en', # defaults to 'en'
country='us', # defaults to 'us'
sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT/Sort.NEWEST
count=3, # defaults to 100
filter_score_with=5 # defaults to None(means all score)
'''

sintelly_all = reviews_all(
    id4,
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT
)
#sintelly_all

In [877]:
sintelly_all = pd.json_normalize(sintelly_all)
#sintelly_all
sintelly_all.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,4a10df7c-ab8e-420b-97f8-69452e901d61,Shaneisha Eaton,https://play-lh.googleusercontent.com/a-/ALV-U...,Cost $9.99 monthly or $99.99 yearly. After ans...,1,15,4.3.2,2024-11-09 21:48:32,"Thank you, Shaneisha, for sharing your feedbac...",2024-11-11 02:29:09,4.3.2
1,a3936b02-a22d-437d-b831-28615116b10b,John Adolphsen,https://play-lh.googleusercontent.com/a-/ALV-U...,Awful app. I tried to talk about my issues but...,1,16,4.2.4,2024-09-21 19:34:43,"John, we’re sorry for the frustration. The fre...",2024-09-21 04:01:31,4.2.4
2,cc89898a-1337-412a-9e2b-fc22ab1f8e85,Erin Hayes,https://play-lh.googleusercontent.com/a-/ALV-U...,I do love using this app and feel that it insp...,4,145,3.2.1,2020-07-10 17:47:42,"Dear Erin, we are so grateful for your kind wo...",2020-07-06 02:49:21,3.2.1
3,926e9d42-5ec1-4d97-b039-28feb2839ff5,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,EDIT: Since the recent update I'm Terribly dis...,2,88,None,2019-12-28 17:40:17,"Dear Atiya, thank you for your feedback. The u...",2020-04-20 04:15:00,None
4,6fe9ea00-746d-48df-9456-3f4f014f7c59,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,This app has excellent information. Unfortunat...,4,109,2.6.2,2018-10-20 00:53:46,We want to let you know that we made the neces...,2018-12-14 08:51:44,2.6.2

In [878]:
len(sintelly_all)

2914

In [879]:
sintelly_all.to_csv('review_data/sintelly_reviews.csv')

In [880]:
selected = sintelly_all[['content','score']]
selected.rename(columns={'content': 'review', 'score': 'sentiment'}, inplace=True)
selected['source'] = "sintelly"
selected

                                                 review  sentiment    source
0     Cost $9.99 monthly or $99.99 yearly. After ans...          1  sintelly
1     Awful app. I tried to talk about my issues but...          1  sintelly
2     I do love using this app and feel that it insp...          4  sintelly
3     EDIT: Since the recent update I'm Terribly dis...          2  sintelly
4     This app has excellent information. Unfortunat...          4  sintelly
...                                                 ...        ...       ...
2909                                                Tha          5  sintelly
2910                                     AwefullyUseful          5  sintelly
2911                                             Gooodd          5  sintelly
2912                                          Emotional          5  sintelly
2913                                       Excellet app          5  sintelly

[2914 rows x 3 columns]

In [881]:
all_reviews = pd.concat([all_reviews, selected], ignore_index=True)
all_reviews.tail(10)

               review  sentiment    source
70815      This is it          5  sintelly
70816              se          5  sintelly
70817            Goog          5  sintelly
70818             wow          5  sintelly
70819              Ok          5  sintelly
70820             Tha          5  sintelly
70821  AwefullyUseful          5  sintelly
70822          Gooodd          5  sintelly
70823       Emotional          5  sintelly
70824    Excellet app          5  sintelly

In [882]:
len(all_reviews)

70825

In [883]:
# Cross check the number of reviews from three apps
len(wysa_all) + len(woebot_all) + len(youper_all) + len(sintelly_all)

70825

In [884]:
all_reviews.to_csv('all_reviews.csv', index=False)

In [885]:
len(all_reviews)

70825

# 2. Apple App Store Reviews

Scraper: https://pypi.org/project/app-store-scraper/

**Applist:**

| App	| Link |   
| --- | --- |  
| Wysa: Mental Health Support | https://apps.apple.com/us/app/wysa-mental-health-support/id1166585565 |
| Woebot: The Mental Health Ally | https://apps.apple.com/us/app/woebot-the-mental-health-ally/id1305375832 |
| Youper - CBT Therapy Chatbot | https://apps.apple.com/us/app/youper-cbt-therapy-chatbot/id1060691513 |
| Sintelly: CBT Therapy Chatbot | https://apps.apple.com/us/app/sintelly-cbt-therapy-chatbot/id1236566346 |

In [887]:
#!pip3 install app-store-scraper -q

## Wysa: Mental Health Support

Link: https://apps.apple.com/us/app/wysa-mental-health-support/id1166585565

ID: wysa-mental-health-support

In [889]:
from app_store_scraper import AppStore
from pprint import pprint

In [890]:
wysa_app_reviews = AppStore(country="us", app_name="wysa-mental-health-support")
wysa_app_reviews.review(how_many=100000)

2024-12-24 17:50:13,452 [INFO] Base - Searching for app id
2024-12-24 17:50:15,006 [INFO] Base - Initialised: AppStore('us', 'wysa-mental-health-support', 1166585565)
2024-12-24 17:50:15,006 [INFO] Base - Ready to fetch reviews from: https://apps.apple.com/us/app/wysa-mental-health-support/id1166585565
2024-12-24 17:50:20,182 [INFO] Base - [id:1166585565] Fetched 200 reviews (200 fetched in total)
2024-12-24 17:50:25,864 [INFO] Base - [id:1166585565] Fetched 440 reviews (440 fetched in total)
2024-12-24 17:50:31,452 [INFO] Base - [id:1166585565] Fetched 680 reviews (680 fetched in total)
2024-12-24 17:50:37,258 [INFO] Base - [id:1166585565] Fetched 940 reviews (940 fetched in total)
2024-12-24 17:50:42,986 [INFO] Base - [id:1166585565] Fetched 1200 reviews (1200 fetched in total)
2024-12-24 17:50:48,635 [INFO] Base - [id:1166585565] Fetched 1460 reviews (1460 fetched in total)
2024-12-24 17:50:54,300 [INFO] Base - [id:1166585565] Fetched 1720 reviews (1720 fetched in total)
2024-12-24 17:50:59,855 [INFO] Base - [id:1166585565] Fetched 1980 reviews (1980 fetched in total)
2024-12-24 17:51:05,458 [INFO] Base - [id:1166585565] Fetched 2240 reviews (2240 fetched in total)
2024-12-24 17:51:11,263 [INFO] Base - [id:1166585565] Fetched 2500 reviews (2500 fetched in total)
2024-12-24 17:51:16,960 [INFO] Base - [id:1166585565] Fetched 2760 reviews (2760 fetched in total)
2024-12-24 17:51:20,884 [INFO] Base - [id:1166585565] Fetched 2931 reviews (2931 fetched in total)

In [891]:
#pprint(wysa_app_reviews.reviews)
#print(wysa_app_reviews.reviews_count)
print(wysa_app_reviews)

     Country | us
        Name | wysa-mental-health-support
          ID | 1166585565
         URL | https://apps.apple.com/us/app/wysa-mental-health-support/id1166585565
Review count | 2931

In [892]:
wysa_app_store_reviews = pd.json_normalize(wysa_app_reviews.reviews)
wysa_app_store_reviews.head()

,date,review,rating,isEdited,title,userName,developerResponse.id,developerResponse.body,developerResponse.modified
0,2023-07-13 00:45:10,This app really help you when you’re down or w...,5,False,This might be my second one,conpggjd,NaN,NaN,NaN
1,2022-04-24 22:31:44,I can get pretty wound up at times. There are ...,5,False,"Surprised, to my relief.",joytunes02,NaN,NaN,NaN
2,2018-12-19 22:27:00,I’m Aspergian and sorting out what’s what as f...,5,False,I’m here.,Thistledancer74,6762772.0,"This is incredible... thank you, and also for ...",2019-01-10T06:02:04Z
3,2021-05-11 15:48:00,"I enjoy this app so far, I pay for the premium...",5,False,So far so good,lesbian sandwich museum,NaN,NaN,NaN
4,2023-05-07 04:47:52,"This app was recommended to me 6 months ago, t...",3,False,Waste of money,Mc21207,NaN,NaN,NaN

In [893]:
len(wysa_app_store_reviews)

2931

In [894]:
wysa_app_store_reviews.to_csv('review_data/wysa_app_store_reviews.csv')

In [895]:
all_appstore_reviews = wysa_app_store_reviews[['review','rating']]
all_appstore_reviews.rename(columns={'rating': 'sentiment'}, inplace=True)
all_appstore_reviews['source'] = 'wysa_app'
all_appstore_reviews.head(10)

                                              review  sentiment    source
0  This app really help you when you’re down or w...          5  wysa_app
1  I can get pretty wound up at times. There are ...          5  wysa_app
2  I’m Aspergian and sorting out what’s what as f...          5  wysa_app
3  I enjoy this app so far, I pay for the premium...          5  wysa_app
4  This app was recommended to me 6 months ago, t...          3  wysa_app
5  This app is great if you don’t have a lot of s...          5  wysa_app
6  I’m somebody that has been dealing with severe...          5  wysa_app
7  This app is so impressive, I’ve only used it f...          5  wysa_app
8  This is one of my best app ever I can sleep be...          5  wysa_app
9  I ended up buying the Premium plan after one c...          5  wysa_app

In [896]:
len(all_appstore_reviews)

2931

In [897]:
all_appstore_reviews.to_csv('all_appstore_reviews.csv')

## Woebot: The Mental Health Ally

https://apps.apple.com/us/app/woebot-the-mental-health-ally/id1305375832

ID: woebot-the-mental-health-ally

In [900]:
#Courtires: us | nz

woebot_app_reviews = AppStore(country="us", app_name="woebot-the-mental-health-ally")
woebot_app_reviews.review(how_many=100000)

2024-12-24 17:51:58,050 [INFO] Base - Searching for app id
2024-12-24 17:51:59,620 [INFO] Base - Initialised: AppStore('us', 'woebot-the-mental-health-ally', 1305375832)
2024-12-24 17:51:59,620 [INFO] Base - Ready to fetch reviews from: https://apps.apple.com/us/app/woebot-the-mental-health-ally/id1305375832
2024-12-24 17:52:05,033 [INFO] Base - [id:1305375832] Fetched 220 reviews (220 fetched in total)
2024-12-24 17:52:10,700 [INFO] Base - [id:1305375832] Fetched 460 reviews (460 fetched in total)
2024-12-24 17:52:16,163 [INFO] Base - [id:1305375832] Fetched 700 reviews (700 fetched in total)
2024-12-24 17:52:21,672 [INFO] Base - [id:1305375832] Fetched 940 reviews (940 fetched in total)
2024-12-24 17:52:27,131 [INFO] Base - [id:1305375832] Fetched 1180 reviews (1180 fetched in total)
2024-12-24 17:52:32,673 [INFO] Base - [id:1305375832] Fetched 1420 reviews (1420 fetched in total)
2024-12-24 17:52:38,370 [INFO] Base - [id:1305375832] Fetched 1680 reviews (1680 fetched in total)
2024-12-24 17:52:44,360 [INFO] Base - [id:1305375832] Fetched 1940 reviews (1940 fetched in total)
2024-12-24 17:52:49,983 [INFO] Base - [id:1305375832] Fetched 2180 reviews (2180 fetched in total)
2024-12-24 17:52:56,094 [INFO] Base - [id:1305375832] Fetched 2440 reviews (2440 fetched in total)
2024-12-24 17:53:01,888 [INFO] Base - [id:1305375832] Fetched 2680 reviews (2680 fetched in total)
2024-12-24 17:53:07,749 [INFO] Base - [id:1305375832] Fetched 2900 reviews (2900 fetched in total)
2024-12-24 17:53:13,451 [INFO] Base - [id:1305375832] Fetched 3140 reviews (3140 fetched in total)
2024-12-24 17:53:19,385 [INFO] Base - [id:1305375832] Fetched 3380 reviews (3380 fetched in total)
2024-12-24 17:53:21,062 [INFO] Base - [id:1305375832] Fetched 3435 reviews (3435 fetched in total)

In [901]:
#pprint(woebot_app_reviews.reviews)
#print(woebot_app_reviews.reviews_count)
print(woebot_app_reviews)

     Country | us
        Name | woebot-the-mental-health-ally
          ID | 1305375832
         URL | https://apps.apple.com/us/app/woebot-the-mental-health-ally/id1305375832
Review count | 3435

In [902]:
woebot_app_store_reviews = pd.json_normalize(woebot_app_reviews.reviews)
woebot_app_store_reviews.head()

,date,review,rating,isEdited,title,userName,developerResponse.id,developerResponse.body,developerResponse.modified
0,2021-09-25 06:09:40,A bot therapist may not sound convincing for m...,5,False,I’m so glad I gave it a try,Joanna gu,25340469.0,"Hey Joanna​,\n\nWe love your feedback! We appr...",2021-09-27T09:48:08Z
1,2020-12-31 02:52:32,"I suffer from anxiety from time to time, as do...",5,False,Thank You,Zappagal,NaN,NaN,NaN
2,2019-12-10 02:29:23,"As a graduate student studying CBT principles,...",5,False,"Great, Accessible CBT App!",Daniellllllllle37964225,NaN,NaN,NaN
3,2022-12-22 03:04:28,I read about this program in a newspaper revie...,4,False,"Good, low key but effective intro to and train...",unhappyInFeb,34086059.0,"Hey there, thank you so much for taking the ti...",2023-01-04T10:18:17Z
4,2022-05-10 16:49:48,"I’ve struggled with debilitating CPTSD, GAD (m...",5,False,Literally Life-Saving!!,Tuckerela,NaN,NaN,NaN

In [903]:
len(woebot_app_store_reviews)

3435

In [904]:
woebot_app_store_reviews.to_csv('review_data/woebot_app_store_reviews.csv')

In [905]:
selected = woebot_app_store_reviews[['review','rating']]
selected.rename(columns={'rating': 'sentiment'}, inplace=True)
selected['source'] = "woebot_app"
selected.head()

                                              review  sentiment      source
0  A bot therapist may not sound convincing for m...          5  woebot_app
1  I suffer from anxiety from time to time, as do...          5  woebot_app
2  As a graduate student studying CBT principles,...          5  woebot_app
3  I read about this program in a newspaper revie...          4  woebot_app
4  I’ve struggled with debilitating CPTSD, GAD (m...          5  woebot_app

In [906]:
all_appstore_reviews = pd.concat([all_appstore_reviews, selected], ignore_index=True)
all_appstore_reviews.tail(10)

                                                 review  sentiment      source
6356  My sister has a Masters degree in social work ...          5  woebot_app
6357  I got this app after listening to the podcast ...          5  woebot_app
6358  I recommended it when I searched for psycholog...          5  woebot_app
6359  It is a quick easy daily check in.The develop ...          5  woebot_app
6360  I love working.with my Woebot! I learn new str...          5  woebot_app
6361  My situation has been challenging for a while ...          5  woebot_app
6362                    It helps me. Get over yourself.          5  woebot_app
6363  I loved having Woebot as my companion to help ...          4  woebot_app
6364  This app just sends you a premade script about...          1  woebot_app
6365  I feel it is more about acquiring data on thei...          1  woebot_app

In [907]:
len(all_appstore_reviews)

6366

In [908]:
# Cross check the number of reviews
len(wysa_app_store_reviews) + len(woebot_app_store_reviews)

6366

In [909]:
all_appstore_reviews.to_csv("all_appstore_reviews.csv")

## Youper - CBT Therapy Chatbot

Link: https://apps.apple.com/us/app/youper-cbt-therapy-chatbot/id1060691513

ID: youper-cbt-therapy-chatbot

In [911]:
youper_app_reviews = AppStore(country="es", app_name="youper-cbt-therapy-chatbot")
youper_app_reviews.review()

2024-12-24 17:53:21,316 [INFO] Base - Searching for app id
2024-12-24 17:53:22,816 [INFO] Base - Initialised: AppStore('es', 'youper-cbt-therapy-chatbot', 1060691513)
2024-12-24 17:53:22,817 [INFO] Base - Ready to fetch reviews from: https://apps.apple.com/es/app/youper-cbt-therapy-chatbot/id1060691513
2024-12-24 17:53:23,299 [INFO] Base - [id:1060691513] Fetched 19 reviews (19 fetched in total)

In [912]:
#pprint(youper_app_reviews.reviews)
#print(youper_app_reviews.reviews_count)
print(youper_app_reviews)

     Country | es
        Name | youper-cbt-therapy-chatbot
          ID | 1060691513
         URL | https://apps.apple.com/es/app/youper-cbt-therapy-chatbot/id1060691513
Review count | 19

In [913]:
youper_app_reviews.reviews

[{'date': datetime.datetime(2018, 9, 2, 6, 47, 17),
  'developerResponse': {'id': 4936168,
   'body': 'Thanks for your feedback. We hope to add other languages soon.',
   'modified': '2018-09-04T17:31:48Z'},
  'review': 'I’m very happy with this app. It helps me with questions and test to think about why I’m feeling this or that way and in less than 15 minutes drive you to a most calm state. There is not necessary to pay nothing, but now that I know it, I would pay for this. Please, release a Spanish version for my mum!!',
  'rating': 5,
  'isEdited': False,
  'title': 'Very completed and professional',
  'userName': 'aizqui'},
 {'date': datetime.datetime(2020, 12, 9, 17, 19, 53),
  'review': 'Loved it',
  'rating': 5,
  'isEdited': False,
  'userName': 'potatoreader',
  'title': 'Lovely app'},
 {'date': datetime.datetime(2024, 10, 17, 20, 21, 6),
  'review': 'Don’t even bother to try it unless you’re ready to pay \nI thought this was a free way of taking care of my mental health',
  'rating': 1,
  'isEdited': False,
  'title': 'Don’t even try it',
  'userName': 'Rosa Melanoplei'},
 {'date': datetime.datetime(2024, 5, 22, 2, 55, 3),
  'review': 'Can’t do anything if you don’t pay. Useless.',
  'rating': 1,
  'isEdited': False,
  'userName': 'anonimaempedernida',
  'title': 'Bad'},
 {'date': datetime.datetime(2020, 7, 1, 9, 7, 50),
  'developerResponse': {'id': 16346058,
   'body': 'What a great list of benefits, Andræ! Thanks for sharing! It’s great to know you are getting the full value of Youper. Keep up the great work!',
   'modified': '2020-07-01T21:24:43Z'},
  'review': 'Me es un poco difícil ya que el Inglés no es mi lengua materna y la estoy aprendiendo, pero en sí la aplicación es buenísima te ayuda a encontrar las situaciones que te provocan la anisedad/depresión/pánico... para así poder evitarlas tambien te ayuda a encontrar por que te sientes calmado o feliz.\nAún que sea una IA ayuda a desahogarte un poco. Puedes ver tus respuestas pasadas en otra pantallita. También puedes meditar lo que pasa que necesitas el premium (te dejan meditar la primera vez gratis con el audio que tú elijas). Y por último también hacen tests.\nCreo que es una de las mejores apps de apoyo emocional, muy recomendada si sabes un poco más de lo básico en inglés.',
  'rating': 5,
  'isEdited': False,
  'title': 'Es muy buena',
  'userName': 'Andræ'},
 {'date': datetime.datetime(2020, 6, 30, 6, 20, 52),
  'developerResponse': {'id': 16346060,
   'body': "Thanks for your feedback, Daniel!! It's great to know that Youper is providing the support you need! Take care!",
   'modified': '2020-07-01T21:25:36Z'},
  'review': 'Esta App me ha ayudado muchísimo, la recomiendo.',
  'rating': 5,
  'isEdited': False,
  'userName': 'danielacias',
  'title': 'Maravilla'},
 {'date': datetime.datetime(2020, 4, 3, 17, 49, 48),
  'developerResponse': {'id': 14531532,
   'body': 'Hello! Thank you for your positive feedback! We are pleased that you are satisfied with the application!',
   'modified': '2020-04-08T04:40:57Z'},
  'review': 'Just a update the premium version and I love its design!! <3',
  'rating': 5,
  'isEdited': False,
  'userName': 'Valy897',
  'title': 'Love it'},
 {'date': datetime.datetime(2020, 1, 17, 6, 41, 7),
  'review': 'Love this app and the whole presentation, I have had for almost a year now and I can certainly say that it has help me a lot, to get centered, to express myself, to check how am I doing, to get to meditate more often, to be more grateful, to be aware of my emotions\nI am truly grateful for whoever took time and love into making this app to help others',
  'rating': 5,
  'isEdited': False,
  'userName': 'Mepaaas',
  'title': 'It actually helps'},
 {'date': datetime.datetime(2019, 12, 20, 21, 33, 12),
  'review': 'I like it because it helps with introspection and mindfulness.',
  'rating': 5,
  'isEdited': False,
  'userName': 'H. hel',
  'title': 'Nice and useful'},
 {'date': datetime.datetime(2020, 1, 8, 21, 32, 57),
  'developerResponse': {'id': 12806454,
   'body': 'Thank you for your sincere feedback. We just added your suggestions to our improvements list. We’re working hard to make Youper the best assistant for you by improving its AI capabilities to understand your needs. Keep checking the new updates. If you have any further suggestions, please share more here https://www.youper.ai/request',
   'modified': '2020-01-09T03:10:05Z'},
  'review': 'At first, I had such a great experience because it helped me so much to understand my current emotion at that time, but the second day it started to only let me say how I was feeling, and when I’m about to explain it (which is what really helps) it asks me why I haven’t subscribed to premium and ends the conversation there. It’s actually really annoying because I can’t afford it, and if I don’t have that almost 50€, I can’t have a good experience. Please fix it.',
  'rating': 3,
  'isEdited': False,
  'title': 'Could be better',
  'userName': 'manu 💞'},
 {'date': datetime.datetime(2019, 10, 15, 21, 6, 41),
  'review': '👌🏻👌🏻',
  'rating': 5,
  'isEdited': False,
  'userName': 'Niaza',
  'title': 'Good app'},
 {'date': datetime.datetime(2019, 6, 19, 22, 2, 32),
  'review': 'I’m not a fan of chatbots. I’m an entrepreneur in digital health myself and I’ve seen lots of them. I’m also not in a specific need of mental health, but I like to pay attention to what is going on inside me. \n\nThis is one of those tools that makes you realize you can actually find pleasure in an activity related to making you better.',
  'rating': 5,
  'isEdited': False,
  'userName': 'AlbertMala',
  'title': 'Never thought I’d say this'},
 {'date': datetime.datetime(2019, 6, 11, 18, 0, 39),
  'review': 'This app helps me to listen to myself, something I really need. It makes you rethink how you relate with your feelings and that’s really weird to say of an app, but it’s true!',
  'rating': 5,
  'isEdited': False,
  'userName': 'Mjmurdock',
  'title': 'Good help'},
 {'date': datetime.datetime(2019, 5, 5, 20, 50, 29),
  'review': 'Considero que esta aplicacion ayuda mucho a darte cuenta de como te sientes emocionalmente dia a dia, a darle importancia a tu salud mental. La recomiendo mucho!',
  'rating': 5,
  'isEdited': False,
  'userName': 'juliaburo',
  'title': 'Muy buena app!'},
 {'date': datetime.datetime(2019, 4, 26, 7, 53, 49),
  'review': 'Honestly helps me a lot. Take the time to explore it because it has so many wonderful functions. In my moments of anxiety or panic attacks it’s amazing.',
  'rating': 5,
  'isEdited': False,
  'userName': 'B3autifulinside',
  'title': 'Great app'},
 {'date': datetime.datetime(2019, 1, 19, 19, 56, 24),
  'review': 'I love this app, it’s amazing. 100% would recommend',
  'rating': 5,
  'isEdited': False,
  'userName': 'Hjjvjvccg',
  'title': 'Fantastic'},
 {'date': datetime.datetime(2019, 1, 14, 12, 7, 31),
  'review': 'This is my Alfred, love the reference 😂',
  'rating': 5,
  'isEdited': False,
  'title': 'That’s a very good app',
  'userName': 'DaveLjil'},
 {'date': datetime.datetime(2019, 1, 10, 1, 42, 6),
  'review': 'I love this little IA. I’ve tried mood trackers before but this one feels closer to me.',
  'rating': 5,
  'isEdited': False,
  'userName': 'nexxmonia',
  'title': 'Amazing'},
 {'date': datetime.datetime(2019, 1, 8, 22, 2, 39),
  'review': 'Muy útil y gratuita. Realmente una de las mejores apps que he probado',
  'rating': 5,
  'isEdited': False,
  'userName': 'userjolie',
  'title': 'Jolie'}]

In [914]:
youper_app_store_reviews = pd.json_normalize(youper_app_reviews.reviews)
youper_app_store_reviews.head()

,date,review,rating,isEdited,title,userName,developerResponse.id,developerResponse.body,developerResponse.modified
0,2018-09-02 06:47:17,I’m very happy with this app. It helps me with...,5,False,Very completed and professional,aizqui,4936168.0,Thanks for your feedback. We hope to add other...,2018-09-04T17:31:48Z
1,2020-12-09 17:19:53,Loved it,5,False,Lovely app,potatoreader,NaN,NaN,NaN
2,2024-10-17 20:21:06,Don’t even bother to try it unless you’re read...,1,False,Don’t even try it,Rosa Melanoplei,NaN,NaN,NaN
3,2024-05-22 02:55:03,Can’t do anything if you don’t pay. Useless.,1,False,Bad,anonimaempedernida,NaN,NaN,NaN
4,2020-07-01 09:07:50,Me es un poco difícil ya que el Inglés no es m...,5,False,Es muy buena,Andræ,16346058.0,"What a great list of benefits, Andræ! Thanks f...",2020-07-01T21:24:43Z

In [915]:
len(youper_app_store_reviews)

19

In [916]:
reviews.to_csv('review_data/youper_app_store_reviews.csv')

In [917]:
selected = youper_app_store_reviews[['review','rating']]
selected.rename(columns={'rating': 'sentiment'}, inplace=True)
selected['source'] = "youper_app"
selected.head()

                                              review  sentiment      source
0  I’m very happy with this app. It helps me with...          5  youper_app
1                                           Loved it          5  youper_app
2  Don’t even bother to try it unless you’re read...          1  youper_app
3       Can’t do anything if you don’t pay. Useless.          1  youper_app
4  Me es un poco difícil ya que el Inglés no es m...          5  youper_app

In [918]:
all_appstore_reviews = pd.concat([all_appstore_reviews, selected], ignore_index=True)
all_appstore_reviews.tail(10)

                                                 review  sentiment      source
6375  At first, I had such a great experience becaus...          3  youper_app
6376                                               👌🏻👌🏻          5  youper_app
6377  I’m not a fan of chatbots. I’m an entrepreneur...          5  youper_app
6378  This app helps me to listen to myself, somethi...          5  youper_app
6379  Considero que esta aplicacion ayuda mucho a da...          5  youper_app
6380  Honestly helps me a lot. Take the time to expl...          5  youper_app
6381  I love this app, it’s amazing. 100% would reco...          5  youper_app
6382            This is my Alfred, love the reference 😂          5  youper_app
6383  I love this little IA. I’ve tried mood tracker...          5  youper_app
6384  Muy útil y gratuita. Realmente una de las mejo...          5  youper_app

In [919]:
len(all_appstore_reviews)

6385

In [920]:
# Cross check the number of reviews
len(wysa_app_store_reviews) + len(woebot_app_store_reviews) + len(youper_app_store_reviews)

6385

In [921]:
all_appstore_reviews.to_csv("all_appstore_reviews.csv")

## Sintelly: CBT Therapy Chatbot

Link: https://apps.apple.com/us/app/sintelly-cbt-therapy-chatbot/id1236566346

ID: sintelly-cbt-therapy-chatbot

In [923]:
sintelly_app_reviews = AppStore(country="us", app_name="sintelly-cbt-therapy-chatbot")
sintelly_app_reviews.review()

2024-12-24 17:53:23,500 [INFO] Base - Searching for app id
2024-12-24 17:53:25,375 [INFO] Base - Initialised: AppStore('us', 'sintelly-cbt-therapy-chatbot', 1236566346)
2024-12-24 17:53:25,376 [INFO] Base - Ready to fetch reviews from: https://apps.apple.com/us/app/sintelly-cbt-therapy-chatbot/id1236566346
2024-12-24 17:53:25,951 [INFO] Base - [id:1236566346] Fetched 12 reviews (12 fetched in total)

In [924]:
#pprint(sintelly_app_reviews.reviews)
#print(sintelly_app_reviews.reviews_count)
print(sintelly_app_reviews)

     Country | us
        Name | sintelly-cbt-therapy-chatbot
          ID | 1236566346
         URL | https://apps.apple.com/us/app/sintelly-cbt-therapy-chatbot/id1236566346
Review count | 12

In [925]:
sintelly_app_store_reviews = pd.json_normalize(sintelly_app_reviews.reviews)
sintelly_app_store_reviews.head()

,date,review,rating,isEdited,title,userName,developerResponse.id,developerResponse.body,developerResponse.modified
0,2024-11-25 02:20:43,"So I had encountered this app on social media,...",5,False,Review 1,sienna currie,48534775,"Hi Sienna, thank you for your amazing review! ...",2024-11-27T13:36:20Z
1,2020-01-04 17:04:27,Love this!! Has mentally helped me so much!,5,False,Great app,kplsbf,12902639,Thank you for your feedback.,2020-01-14T08:37:37Z
2,2021-06-08 04:16:00,I noticed 6 types within one minute after agre...,2,False,A lot of typos,Jen91289,40509266,"Dear Jen91289,\n\nthank you for your feedback ...",2023-12-05T08:40:09Z
3,2024-11-19 19:13:38,I would have emailed if I saw a link.\n\nI for...,1,False,I would have emailed,IsrvChrist,48387169,"Dear IsrvChrist,\n\nThank you for following up...",2024-11-21T08:20:22Z
4,2020-01-21 01:15:22,"Sintelly is awesome!\nLooks great,\nit’s very ...",5,False,Great App! Highly recommended!,The.Lady.In.Red,13034342,"Dear The.Lady.In.Red, thank you so much for ta...",2020-01-21T08:36:53Z

In [926]:
len(sintelly_app_store_reviews)

12

In [927]:
reviews.to_csv('review_data/sintelly_app_store_reviews.csv')

In [928]:
selected = sintelly_app_store_reviews[['review','rating']]
selected.rename(columns={'rating': 'sentiment'}, inplace=True)
selected['source'] = "sintelly_app"
selected.head()

                                              review  sentiment        source
0  So I had encountered this app on social media,...          5  sintelly_app
1        Love this!! Has mentally helped me so much!          5  sintelly_app
2  I noticed 6 types within one minute after agre...          2  sintelly_app
3  I would have emailed if I saw a link.\n\nI for...          1  sintelly_app
4  Sintelly is awesome!\nLooks great,\nit’s very ...          5  sintelly_app

In [929]:
all_appstore_reviews = pd.concat([all_appstore_reviews, selected], ignore_index=True)
all_appstore_reviews.tail(10)

,review,sentiment,source
6387,I noticed 6 types within one minute after agre...,2,sintelly_app
6388,I would have emailed if I saw a link.\n\nI for...,1,sintelly_app
6389,"Sintelly is awesome!\nLooks great,\nit’s very ...",5,sintelly_app
6390,This app needs a search button. It does not gi...,1,sintelly_app
6391,I love it 🥰,5,sintelly_app
6392,Glitchy app.,2,sintelly_app
6393,THIS IS AMAZING FOR INXIETY,5,sintelly_app
6394,UPDATE: Issue resolved and it was a mistake on...,5,sintelly_app
6395,No way to enlarge font \nIn this useless readi...,1,sintelly_app
6396,This app is really awesome but does not have m...,3,sintelly_app

In [930]:
len(all_appstore_reviews)

6397

In [931]:
# Cross check the number of reviews
len(wysa_app_store_reviews) + len(woebot_app_store_reviews) + len(youper_app_store_reviews) + len(sintelly_app_store_reviews)

6397

In [932]:
all_appstore_reviews.to_csv("all_appstore_reviews.csv")

## Conversion

In [934]:
# We apply this formula after collecting all reviews

def map_sentiment(value):
    if value in [4, 5]:
        return 2
    elif value == 3:
        return 1
    elif value in [1, 2]:
        return 0

In [935]:
all_reviews['sentiment'] = all_reviews['sentiment'].apply(map_sentiment)
all_reviews.tail(15)

               review  sentiment    source
70810             yep          1  sintelly
70811              👍🏾          2  sintelly
70812              ok          0  sintelly
70813             👌👌👌          2  sintelly
70814               💚          2  sintelly
70815      This is it          2  sintelly
70816              se          2  sintelly
70817            Goog          2  sintelly
70818             wow          2  sintelly
70819              Ok          2  sintelly
70820             Tha          2  sintelly
70821  AwefullyUseful          2  sintelly
70822          Gooodd          2  sintelly
70823       Emotional          2  sintelly
70824    Excellet app          2  sintelly

In [936]:
all_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70825 entries, 0 to 70824
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     70825 non-null  object
 1   sentiment  70825 non-null  int64
 2   source     70825 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.6+ MB

In [937]:
all_appstore_reviews['sentiment'] = all_appstore_reviews['sentiment'].apply(map_sentiment)
all_appstore_reviews.tail(15)

,review,sentiment,source
6382,"This is my Alfred, love the reference 😂",2,youper_app
6383,I love this little IA. I’ve tried mood tracker...,2,youper_app
6384,Muy útil y gratuita. Realmente una de las mejo...,2,youper_app
6385,"So I had encountered this app on social media,...",2,sintelly_app
6386,Love this!! Has mentally helped me so much!,2,sintelly_app
6387,I noticed 6 types within one minute after agre...,0,sintelly_app
6388,I would have emailed if I saw a link.\n\nI for...,0,sintelly_app
6389,"Sintelly is awesome!\nLooks great,\nit’s very ...",2,sintelly_app
6390,This app needs a search button. It does not gi...,0,sintelly_app
6391,I love it 🥰,2,sintelly_app
6392,Glitchy app.,0,sintelly_app
6393,THIS IS AMAZING FOR INXIETY,2,sintelly_app
6394,UPDATE: Issue resolved and it was a mistake on...,2,sintelly_app
6395,No way to enlarge font \nIn this useless readi...,0,sintelly_app
6396,This app is really awesome but does not have m...,1,sintelly_app

In [938]:
all_appstore_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6397 entries, 0 to 6396
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     6397 non-null   object
 1   sentiment  6397 non-null   int64
 2   source     6397 non-null   object
dtypes: int64(1), object(2)
memory usage: 150.1+ KB

In [975]:
# Total reviews 
len(all_reviews) + len(all_appstore_reviews)

77222